name: Movie Picture Backend Integration

on:

  workflow_dispatch:

  pull_request:
    branches: 
      - main
    paths:
      - 'starter/backend/**'

jobs:

  lint:
    name: Lint backend Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Ensure flake8 is in Pipfile
        run: |
          cd starter/backend
          pipenv install --dev flake8

      - name: Run Flake8
        run: |
          cd starter/backend
          pipenv run flake8 . --max-line-length=200

      - name: Run ESLint
        run: |
          cd starter/backend
          pipenv run lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Run Tests
        run: |
          cd starter/frontend
          pipenv run test 

  build:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd starter/frontend
          docker build --tag mp-backend:latest .
